#!/bin/bash

# Verifica se foi passado um arquivo
if [ -z "$1" ]; then
    echo "Uso: $0 /caminho/do/video.mp4"
    exit 1
fi

INPUT="$1"

# Verifica se o arquivo existe
if [ ! -f "$INPUT" ]; then
    echo "Arquivo não encontrado."
    exit 1
fi

# Diretório do arquivo original
DIR=$(dirname "$INPUT")

# Nome do arquivo sem extensão
FILENAME=$(basename -- "$INPUT")
NAME="${FILENAME%.*}"

# Extensão original
EXT="${FILENAME##*.}"

# Executa o ffmpeg
ffmpeg -i "$INPUT" \
-c copy \
-map 0 \
-f segment \
-segment_time 20 \
-reset_timestamps 1 \
"$DIR/${NAME}_%02d.$EXT"
